language: node_js
node_js:
- '0.10'
deploy:
  provider: heroku
  api_key:
    secure: grqIdtuhtVOng4kjwNi/bCtNc3OFqrVjnbb919XTw/I3Ep8gRUJ84TPSwqFyggrJPWi/8btBjXYbGSvoYq0UdD59IBU+Y4m2oSd43lrzINf9JZxqSGWTe+sAlmOKP57iBDu+aw/8f6o92IuZiIv3tBhaaLAPXvLPEIDVxLnL+/0=
